# Application URL
base.url=https://trimont-test.appiancloud.com/suite/portal/login.jsp
home.url = https://trimont-test.appiancloud.com/suite/sites/vendor-req/page/home

# Browser & Driver Config
browser=edge
edge.driver.path=C:/Webdrivers/msedgedriver.exe

# Timeouts (optional)
implicit.wait=5
explicit.wait=10

# Existing OC user
existing.username=LegalMngrTest
existing.password=Maantic@2026

# Existing OC task comments
existing.comments=Regression Edge Case - Withdraw flow test

# Existing OC Update Request Description
existing.desc=Request is updated successfully

# Existing OC Cancel Request Justification
existing.jus=Request is cancelled successfully

# New OC user
new.username=LegalMngrTest
new.password=Maantic@2026

# New OC Senior Legal user
newSrLegal.username=LegalSrTeamTest
newSrLegal.password=Maantic@2026

# New OC Vendor Management user
newVenMgr.username=VendorMngrTest
newVenMgr.password=Maantic@2026

# New OC Outside Counsel user
newCounsel.username=CMS_IntTest
newCounsel.password=Maantic@2025

