# New OC flow property list

# OC Firm Name
ocFirmName=Auto New OC Firm 

# OC Justification
justificationText=Auto justification added by automation for Firm 

# OC Attorney
ocAttorney=Auto Attorney 

# OC Phone
ocPhone=1234567890

# OC Email
ocEmail=autouser@mail.com

# City
ocCity=Sitka

ocCities=Chicago,Houston,Phoenix,Boston,Denver,Nashville,Detroit,Dallas,Austin,Portland,Seattle,Cleveland,Miami,Orlando,Columbus

# New OC New Vendor task comments
newVendor.comments=New vendor Rejected Comments 

# New OC New OFAC task comments
newOFAC.comments=New vendor OFAC Rejected Comments 

# Conflict Justification
conJustificationText=Conflict Waiver justification added

# New Conflict Waiver task comments
newConflict.comments=New Conflict Waiver Rejected Comments 

